[package]
cjc-version = "1.0.5"
name = "cui"
version = "0.9.2"
output-type = "static"
description = "Declarative desktop GUI framework for Cangjie"

[dependencies]
sdl = { git = "https://github.com/SunriseSummer/CangjieSDL.git" }
